Check pdftotext

diff --git a/install b/install
--- a/install
+++ b/install
@@ -19,6 +19,25 @@ if ! command -v llama-cli &>/dev/null; then
 	fi
 fi
 
+# Check to see if pdftotext is available
+if ! command -v pdftotext &>/dev/null; then
+  echo "Yo requires pdftotext to be installed. It appears that 'pdftotext' is not installed on your system."
+  read -p "Would you like to install it now? (y/n): " choice
+  if [[ "$choice" =~ ^[yY]$ ]]; then
+    echo "Installing pdftotext..."
+    pip install pdftotext
+    if [ $? -eq 0 ]; then
+      echo "pdftotext has been successfully installed."
+    else
+      echo "There was an error installing pdftotext. Please try installing it manually."
+      return 1
+    fi
+  else
+    echo "Installation canceled. Please install pdftotext and try again."
+    return 1
+  fi
+fi
+
 # Yo to the shell
 zsh <(curl -s https://cmccomb.com/yo/src)
 
