Install checks for gdate

diff --git a/install b/install
--- a/install
+++ b/install
@@ -36,6 +36,15 @@ else
 	echo "pdftotext is already installed."
 fi
 
+# Check to see if gdate is install and install it if it is not
+if ! command -v gdate &>/dev/null; then
+  echo "gdate not found. Installing gdate..."
+  brew install coreutils
+  echo "gdate installation complete."
+else
+  echo "gdate is already installed."
+fi
+
 # Yo to the shell
 echo "Sourcing the Yo script..."
 # shellcheck disable=SC1090
