More encapsulation

diff --git a/src b/src
--- a/src
+++ b/src
@@ -197,15 +197,24 @@ function yo() {
 	### UTILITY FUNCTIONS ################################################################################################
 	######################################################################################################################
 
+	function get_epoch_in_seconds_and_decimals() {
+		gdate +%s.%N
+	}
+
+	function get_value_from_name() {
+		eval echo "\${${variable_name}}"
+	}
+
 	# Check if the input is empty
 	function check_nonempty() {
 
 		# Parse arguments
 		local variable_name=$1
-		local variable_value=$2
 
 		# Check if the input is empty
-		if [[ -z $(eval echo \${${variable_name}}) ]]; then
+		if [[ -z $(get_value_from_name variable_name) ]]; then
+			# shellcheck disable=SC2154
+			# In order to use funcstack with shellcheck, we need to disable SC2154
 			echo "Error in ${funcstack[2]}: Invalid input for ${variable_name}, expected a non-empty string." >&2
 			return 1
 		else
@@ -224,7 +233,7 @@ function yo() {
 
 		# Make variables
 		local variable_value
-		variable_value=$(eval echo \${${variable_name}})
+		variable_value=$(get_value_from_name variable_name)
 
 		# Check if the input is an integer
 		if [[ ! "${variable_value}" =~ ^-?[0-9]+$ ]]; then
@@ -246,7 +255,7 @@ function yo() {
 
 		# Make variables
 		local variable_value
-		variable_value=$(eval echo \${${variable_name}})
+		variable_value=$(get_value_from_name variable_name)
 
 		# Check if the input is Boolean
 		if [[ "${variable_value}" != true && "${variable_value}" != false ]]; then
@@ -268,7 +277,7 @@ function yo() {
 
 		# Make variables
 		local variable_value
-		variable_value=$(eval echo \${${variable_name}})
+		variable_value=$(get_value_from_name variable_name)
 
 		# Check if the input is a float
 		if [[ ! $variable_value =~ ^-?[0-9]*\.?[0-9]+$ ]]; then
@@ -290,7 +299,7 @@ function yo() {
 
 		# Make variables
 		local variable_value
-		variable_value=$(eval echo \${${variable_name}})
+		variable_value=$(get_value_from_name variable_name)
 
 		# Check if the input is a valid path
 		if [[ ! -f "${variable_value}" ]]; then
@@ -312,7 +321,7 @@ function yo() {
 
 		# Make variables
 		local variable_value
-		variable_value=$(eval echo \${${variable_name}})
+		variable_value=$(get_value_from_name variable_name)
 
 		# Check if the input is a valid URL
 		if [[ ! "${variable_value}" =~ ^https?://[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(/.*)?$ ]]; then
@@ -407,7 +416,7 @@ function yo() {
 		local tokens
 
 		# Calculate the number of characters and divide by four
-		tokens=$((((${characters} + CHARACTERS_PER_TOKEN - 1) / CHARACTERS_PER_TOKEN) * TOKEN_ESTIMATION_CORRECTION_FACTOR))
+		tokens=$((((characters + CHARACTERS_PER_TOKEN - 1) / CHARACTERS_PER_TOKEN) * TOKEN_ESTIMATION_CORRECTION_FACTOR))
 
 		# Return result
 		printf "%.0f" "$tokens"
@@ -418,11 +427,9 @@ function yo() {
 
 	# Function to calculate the approximate number of tokens
 	function estimate_number_of_tokens() {
-		# Parse arguments
-		local text=$1
 
-		# Return the estimate
-		characters_to_tokens "${#text}" || {
+		# Estimate the number of tokens
+		characters_to_tokens "${#1}" || {
 			echo "Error: Failed to estimate the number of tokens." >&2
 			return 1
 		}
@@ -706,14 +713,15 @@ function yo() {
 
 		# Create prompt
 		local prompt
-		prompt=$(cat <<-EOF
-			=============== START OF TEXT===============
-			${chunk}
-			=============== END OF TEXT===============
+		prompt=$(
+			cat <<-EOF
+				=============== START OF TEXT===============
+				${chunk}
+				=============== END OF TEXT===============
 
-			Based on the unstructured text given above, provide a concise list of facts and information.
+				Based on the unstructured text given above, provide a concise list of facts and information.
 			EOF
-    )
+		)
 
 		start_llama_session \
 			"${TASK_MODEL_REPO_NAME}" \
@@ -1377,7 +1385,10 @@ function yo() {
 
 	# Save starting time to calculate elapsed time later one
 	local start_time
-	start_time=$(gdate +%s.%N)
+	start_time=$(get_epoch_in_seconds_and_decimals) || {
+		echo "Error: Failed to get the start time." >&2
+		return 1
+	}
 
 	### Configure the model based on whether its a one-off or interactive session ########################################
 	if [[ -n "${query}" ]]; then
@@ -1455,10 +1466,12 @@ function yo() {
 
 	### Print the elapsed time ###########################################################################################
 	tput cuu1 && tput el
-	local end_time elapsed_time
-	end_time=$(gdate +%s.%N)
-	elapsed_time=$(printf "%.2f" "$(echo "${end_time} - ${start_time}" | bc)")
-	timestamp_log_to_stderr "⌛️" "Elapsed time: ${elapsed_time} seconds." >&2
+	local end_time
+	end_time=$(get_epoch_in_seconds_and_decimals) || {
+		echo "Error: Failed to get the end time." >&2
+		return 1
+	}
+	timestamp_log_to_stderr "⌛️" "Elapsed time: $(printf "%.2f" $((end_time - start_time))) seconds." >&2
 
 	### Return success ###################################################################################################
 	return 0
