Formatting

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -4,40 +4,39 @@
 # Keep track of paackages to install
 brew_packages_to_install=()
 dependencies_to_check=(
-  "llama-cli:llama.cpp"
-  "llama-tokenize:llama.cpp"
-  "tesseract:tesseract"
-  "pandoc:pandoc"
-  "pdftotext:poppler"
+	"llama-cli:llama.cpp"
+	"llama-tokenize:llama.cpp"
+	"tesseract:tesseract"
+	"pandoc:pandoc"
+	"pdftotext:poppler"
 )
 
 # Check to see if the command line dependencies are installed and add them to the list if not
 for dependency in "${dependencies_to_check[@]}"; do
-  # The dependency is in the format of "command:package"
-  command="${dependency%%:*}"
-  package="${dependency##*:}"
-  if ! command -v "${command}" &>/dev/null; then
-    brew_packages_to_install+=("${package}")
-  fi
+	# The dependency is in the format of "command:package"
+	command="${dependency%%:*}"
+	package="${dependency##*:}"
+	if ! command -v "${command}" &>/dev/null; then
+		brew_packages_to_install+=("${package}")
+	fi
 done
 
 # Install the command line dependencies
 if [[ ${#brew_packages_to_install} -gt 0 ]]; then
-  # Check to see if homebrew is installed and install it if it is not
-  if ! command -v brew &>/dev/null; then
-    echo "Homebrew not found. Installing Homebrew..."
-    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-    echo "Homebrew installation complete."
-  else
-    echo "Homebrew is already installed."
-  fi
-  echo "Installing command line dependencies..."
-  brew install "${brew_packages_to_install[@]}"
-  echo "Command line dependencies installed."
+	# Check to see if homebrew is installed and install it if it is not
+	if ! command -v brew &>/dev/null; then
+		echo "Homebrew not found. Installing Homebrew..."
+		NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+		echo "Homebrew installation complete."
+	else
+		echo "Homebrew is already installed."
+	fi
+	echo "Installing command line dependencies..."
+	brew install "${brew_packages_to_install[@]}"
+	echo "Command line dependencies installed."
 else
-  echo "Command line dependencies are already installed."
+	echo "Command line dependencies are already installed."
 fi
-
 
 # Download the latest version of yo
 echo "Downloading the latest version of yo..."
